version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"

    restart: "unless-stopped"

    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  piframe-watchtower:
    container_name: "piframe-watchtower"
    image: containrrr/watchtower

    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command: --interval 30

    labels:
      - "traefik.enable=false"


  whoami:
    image: "traefik/whoami"
    container_name: "whoami"

    restart: "unless-stopped"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`piframe`)"
      - "traefik.http.routers.whoami.entrypoints=web"


  piframe:
    image: "conorjf/piframe"
    container_name: "piframe"

    restart: "unless-stopped"

    # Needed for GPIO access.
    privileged: true

    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`piframe`)"
      # - "traefik.http.routers.whoami.entrypoints=web"
