version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"

    restart: "unless-stopped"

    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

    ports:
      - "80:80"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"

    restart: "unless-stopped"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`piframe`)"
      - "traefik.http.routers.whoami.entrypoints=web"
